name: CMake Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install gcovr
      run: pip install gcovr
    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=Debug -DCMAKE_C_COMPILER=gcc -DCMAKE_CXX_COMPILER=g++ -DENABLE_COVERAGE=TRUE
    - name: Build
      run: cmake --build ${{github.workspace}}/build
    - name: Run Tests
      working-directory: ${{github.workspace}}/build
      run: ctest -V
    - name: Generate Coverage Report
      run: |
        cd ${{github.workspace}}/build
        gcovr --exclude 'test/' --html --html-details -o coverage.html .
    - name: Upload Coverage Report to GitHub Pages
      uses: actions/upload-pages-artifact@v2
      with:
        path: ${{github.workspace}}/build/coverage.html

  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
